Cars: 1st request
hassaanalii/Pak-Wheels-Clone pull request #1
Opened 2023-10-02 09:30 UTC by hassaanalii

2023-10-06 10:08 UTC, ibraheem-nadeem requested changes

2023-10-06 10:08 UTC, ibraheem-nadeem commented on cars/views.py
> +        if model == "2020orabove":
This option is only catering to 2020. Is there a better approach to handle other years as well?

Also, we dont use naked strings - please use constants

2023-10-06 10:08 UTC, ibraheem-nadeem commented on cars/views.py
> +    favorite.delete()
Please look into SoftDelete as well

2023-10-06 10:08 UTC, ibraheem-nadeem commented on cars/views.py
> +def favourite_specific_car(request, car_id):
We can approach this in another way:
- If user clicks favourite button, the car gets added as favourite
- If he clicks again, the car will getr un-favourite. 
Both cases can be handled in 1 view

2023-10-06 10:08 UTC, ibraheem-nadeem commented on pakwheelsclone/settings.py
> +SECRET_KEY = 'django-insecure-yi44ql(h2cql*7v2p$#8#zf9!efa!vb8s*!83h_o=84ys=kz^+'
Please load these from .env file

2023-10-06 10:08 UTC, ibraheem-nadeem commented on pakwheelsclone/settings.py
> +        'PORT': '5432'
These should also be loaded from .env

2023-10-07 08:17 UTC, hassaanalii commented on cars/forms.py
> +        self.fields['password2'].label = 'Confirm Password'
Password1 and Password2 are the inbuilt fields in the UserCreationForm

2023-10-07 08:28 UTC, hassaanalii commented on cars/manager.py
> +    def create_superuser(self, phone_number, password, **extra_fields):
create_superuser is implemented because I am using a custom user model, that is why create_superuser is necessary for creating and managing super users

2023-10-07 16:46 UTC, merged